#! /bin/sh

# Start polybar
$HOME/.config/polybar/launch.sh

bspc monitor -d I II III IV V

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config single_monocle       true

# Manipulation of windows
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action1 resize_corner
bspc config pointer_motion_interval 7

